version: '3.7'

services:
  db:
    container_name: fullcycle_db_mysql
    image: mysql:latest
    tty: true
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fulldb
    ports:
      - 3306:3306
    networks:
      - fullnet
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/

  api:
    container_name: fullcycle_api_node
    build:
      context: ./node
    tty: true
    volumes:
      - ./node:/app
    ports:
      - 8080:8080
    networks:
      - fullnet
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm run dev'
  
  # nginx:

networks:
  fullnet:
    driver: bridge
