version: '3.7'

services:
  db:
    container_name: fullcycle_db_mysql
    image: mysql:latest
    tty: true
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fulldb
    networks:
      - fullnet
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/

  api:
    container_name: fullcycle_api_node
    build:
      context: ./node
    tty: true
    volumes:
      - ./node:/app
    networks:
      - fullnet
    depends_on:
      - db
    command: wait-for-it db:3306 -t 30 -- npm run dev

  nginx:
    container_name: fullcycle_nginx
    build:
      context: ./nginx
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - fullnet
    depends_on:
      - api
    command: wait-for-it api:3000 -t 30 -- nginx -g "daemon off;"


networks:
  fullnet:
    driver: bridge
